
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: intall swag
        run: go get -u github.com/swaggo/swag/cmd/swag
        
      - name: run swag
        run: $GOPATH/bin/swag init
        
      - name: mod tidy
        run: go mod tidy

      - name: build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
